technology_innovation = [
    "AI",
    "API",
    "AR/VR",
    "Automation",
    "CleanTech/Environment",
    "Cloud Infrastructure",
    "Cryptocurrency/Blockchain",
    "Cybersecurity",
    "Data Services",
    "DeepTech",
    "Developer Tools",
    "Digital Health",
    "EnergyTech",
    "Enterprise Applications",
    "Enterprise Infrastructure",
    "FinTech",
    "IoT",
    "Robotics",
    "SaaS",
    "Security",
    "Semiconductors",
    "Web3",
    "Robotics/Drones/Autonomous Systems",
    "AI/ML",
    "Smart City",
    "5G & Telecommunications",
    "Web3 & Blockchain",
    "Cloud",
]

business_commerce = [
    "Advertising",
    "B2B SaaS",
    "B2C/E-Commerce",
    "Commercial Services",
    "Consumer",
    "Consumer Durables",
    "Consumer Non-Durables",
    "Direct-to-Consumer (DTC)",
    "E-Commerce",
    "Enterprise",
    "Financial Services",
    "Marketplaces",
    "Payments",
    "Retail",
    "SMB Software",
    "Retail Tech",
    "MarketingTech",
    "B2C",
    "Enterprise Software",
]

healthcare_wellness = [
    "BioTech",
    "Consumer Health",
    "Health & Hospital Services",
    "Health and Wellness",
    "Healthcare/MedTech",
    "Medical Devices",
    "Pharmaceuticals",
    "Wellness & Fitness",
    "Health & Medical Devices",
    "Mental Health",
    "Health IT",
    "Beauty & wellness",
    "Beauty",
    "Biotech & Genetech",
    "MedTech & Healthcare",
]

agriculture_food = [
    "AgTech",
    "Food & Agriculture",
    "Food and Beverage",
    "Agritech",
    "Foodtech",
    "Food & Ag",
]

education_learning = ["EdTech", "Education"]

real_estate_property = ["ConstructionTech", "Proptech", "Real Estate"]

entertainment_media = [
    "Entertainment",
    "Game Development",
    "Gaming/eSports",
    "Media",
    "Messaging",
    "Sports",
    "Travel",
    "Entertainment & Sports",
    "Media & Advertising",
    "Media/Content",
    "Gaming",
    "Social Media",
    "Adtech",
]

industry_manufacturing = [
    "Chemicals",
    "Industrial",
    "Manufacturing",
    "Material Science",
    "Hard Tech & Manufacturing",
    "Renewable Energy",
    "Sustainability & Energy",
]

hr_work = [
    "Future of Work",
    "Gig Economy",
    "Gov & Legal",
    "GovTech",
    "Government Technology",
    "HRTech",
    "Human Capital/HRTech",
    "IT Services",
    "Impact",
    "Insurance",
    "Logistics",
    "Mobility",
    "Supply Chain",
    "Transportation",
    "TransportationTech",
    "Legaltech",
    "Transport",
    "Supply Chain & Logistics",
    "Future of Work & Productivity",
]

other_sectors = [
    "Capital Markets",
    "Climate",
    "Defense",
    "Fashion",
    "Hardware",
    "Life Sciences",
    "Local Services",
    "Lodging/Hospitality",
    "Parenting/Families",
    "Productivity",
    "Sales & CRM",
    "Social Commerce",
    "Social Networks",
    "Space",
    "InsureTech",
    "Analytics",
    "CleanTech",
    "Aerospace",
    "Industry Agnostic",
    "New Materials & Packaging",
]

aggregate = {
    "Technology & Innovation": technology_innovation,
    "Business & Commerce": business_commerce,
    "Healthcare & Wellness": healthcare_wellness,
    "Agriculture & Food": agriculture_food,
    "Education & Learning": education_learning,
    "Real Estate & Property": real_estate_property,
    "Entertainment & Media": entertainment_media,
    "Industry & Manufacturing": industry_manufacturing,
    "HR & Work": hr_work,
    "Other Sectors": other_sectors,
}
