"""empty message

Revision ID: 0558ba631472
Revises: 5c32ad357046
Create Date: 2024-07-15 03:34:38.896802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '0558ba631472'
down_revision = '5c32ad357046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_invitation',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'EMPLOYEE', name='companyrole'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'EMPLOYEE', name='companyrole'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # conn = op.get_bind()
    # companies = conn.execute(text("SELECT id, user_id FROM company")).fetchall()
    # for company in companies:
    #     conn.execute(
    #         text(
    #             "INSERT INTO user_company (user_id, company_id, role, is_primary, is_public) VALUES (:user_id, :company_id, 'OWNER', TRUE, FALSE)"
    #         ),
    #         {'user_id': company[1], 'company_id': company[0]}
    #     )
    op.drop_table('waitlist_charge')
    op.drop_table('waitlist')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint('company_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('investment_firm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_firm', schema=None) as batch_op:
        batch_op.drop_column('twitter')
        batch_op.drop_column('linkedin')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('company_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    op.create_table('waitlist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='waitlist_pkey'),
    sa.UniqueConstraint('email', name='waitlist_email_key')
    )
    op.create_table('waitlist_charge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('charge_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('customer_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('random_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('downloaded', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='waitlist_charge_pkey')
    )
    op.drop_table('user_company')
    op.drop_table('company_invitation')
    # ### end Alembic commands ###
