"""baseline schema

Revision ID: 1e3561d00b0f
Revises: 
Create Date: 2026-06-25 15:35:11.598067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3561d00b0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'ORG', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('IDEA', 'PRE_SEED', 'SEED', 'SERIES_A', 'SERIES_B', 'SERIES_C', 'SERIES_D_PLUS', 'GROWTH', 'LATE_STAGE', 'DEBT', 'SECONDARY', name='investment_stage'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'stage', name='uq_entity_stage')
    )
    op.create_table('geography',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('investor_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'ORG', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('investor_type', sa.Enum('ANGEL', 'ANGEL_SYNDICATE', 'ANGEL_GROUP', 'SCOUT', 'MICRO_VC', 'VC_FIRM', 'GROWTH_EQUITY', 'CORPORATE_VC', 'ACCELERATOR', 'INCUBATOR', 'VENTURE_STUDIO', 'FAMILY_OFFICE', 'PRIVATE_EQUITY', 'VENTURE_DEBT', 'CROWDFUNDING_PLATFORM', 'GRANT_PROGRAM', 'GOVERNMENT_PROGRAM', 'SEARCH_FUND', 'FUND_OF_FUNDS', 'LIMITED_PARTNER', 'HEDGE_FUND', 'OTHER', name='investor_type'), nullable=True),
    sa.Column('min_investment', sa.BigInteger(), nullable=True),
    sa.Column('max_investment', sa.BigInteger(), nullable=True),
    sa.Column('n_investments', sa.Integer(), nullable=True),
    sa.Column('n_exits', sa.Integer(), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('lead_pref', sa.Enum('LEAD', 'FOLLOW', 'BOTH', 'UNKNOWN', name='lead_preference'), nullable=True),
    sa.Column('accepts_cold_inbound', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_investor_profile_entity')
    )
    op.create_table('notable_investment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('claim_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'ORG', name='entity_type'), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('status_info', sa.String(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'ORG', name='entity_type'), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'ORG', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', name='uq_entity_bookmark_user_entity')
    )
    op.create_table('entity_geography',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'ORG', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('geography_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geography_id'], ['geography.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'geography_id', name='uq_entity_geography')
    )
    op.create_table('entity_industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'ORG', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'industry_id', name='uq_entity_industry')
    )
    op.create_table('entity_notable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'ORG', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('notable_investment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notable_investment_id'], ['notable_investment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'notable_investment_id', name='uq_entity_notable')
    )
    op.create_table('login_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('json_data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('org_type', sa.Enum('VC_FIRM', 'MICRO_VC', 'ANGEL_GROUP', 'CORPORATE_VC', 'FAMILY_OFFICE', 'ACCELERATOR', 'INCUBATOR', 'VENTURE_STUDIO', 'PE_FIRM', 'GROWTH_EQUITY', 'SYNDICATE', 'LP_FUND_OF_FUNDS', 'GRANT_PROGRAM', 'GOVERNMENT_PROGRAM', 'VENTURE_DEBT', 'CROWDFUNDING_PLATFORM', 'SEARCH_FUND', 'HEDGE_FUND', 'OTHER', name='org_type'), nullable=False),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('n_employees', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_index', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('source', 'source_id', name='uq_organization_source')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_index', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('source', 'source_id', name='uq_person_source')
    )
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.Enum('INVESTOR', 'INVESTMENT_FIRM', 'COMPANY', 'PERSON', 'ORG', name='searchhistorytype'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('twitter_url', sa.String(), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('email_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('linkedin_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('instagram_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('twitter_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PREMIUM_MONTHLY', 'PREMIUM_YEARLY', name='tier'), nullable=False),
    sa.Column('is_pro', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pro_source', sa.String(), nullable=True),
    sa.Column('pro_expires_at', sa.DateTime(), nullable=True),
    sa.Column('paddle_customer_id', sa.String(), nullable=True),
    sa.Column('paddle_subscription_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('affiliation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('FOUNDER', 'GP', 'PARTNER', 'PRINCIPAL', 'ASSOCIATE', 'SCOUT', 'ADVISOR', 'LP', 'OPERATOR', name='affiliation_role'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'organization_id', 'role', name='uq_affiliation_person_org_role')
    )
    # ### end Alembic commands ###

    # --- Seed the bootstrap admin (OTP sign-in; no password by design) ---
    # Idempotent: only inserts if the account is absent, so re-running upgrade
    # against an already-seeded DB is a no-op.
    op.execute(
        """
        INSERT INTO "user" (email, is_verified, is_admin)
        SELECT 'arstan.usenov@gmail.com', true, true
        WHERE NOT EXISTS (SELECT 1 FROM "user" WHERE email = 'arstan.usenov@gmail.com');

        INSERT INTO user_info (user_id, first_name, last_name, username, is_complete)
        SELECT u.id, 'Arstan', 'Usenov', 'barnacle', true
        FROM "user" u
        WHERE u.email = 'arstan.usenov@gmail.com'
          AND NOT EXISTS (SELECT 1 FROM user_info ui WHERE ui.user_id = u.id);

        INSERT INTO user_payment (user_id, is_active, tier, is_pro)
        SELECT u.id, false, 'FREE', false
        FROM "user" u
        WHERE u.email = 'arstan.usenov@gmail.com'
          AND NOT EXISTS (SELECT 1 FROM user_payment up WHERE up.user_id = u.id);
        """
    )


def downgrade():
    op.execute("DELETE FROM \"user\" WHERE email = 'arstan.usenov@gmail.com'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliation')
    op.drop_table('user_payment')
    op.drop_table('user_info')
    op.drop_table('search_history')
    op.drop_table('person')
    op.drop_table('organization')
    op.drop_table('notification')
    op.drop_table('login_token')
    op.drop_table('entity_notable')
    op.drop_table('entity_industry')
    op.drop_table('entity_geography')
    op.drop_table('entity_bookmark')
    op.drop_table('email_verification')
    op.drop_table('claim_verification')
    op.drop_table('claim_request')
    op.drop_table('user')
    op.drop_table('round')
    op.drop_table('processed_webhook')
    op.drop_table('notable_investment')
    op.drop_table('investor_profile')
    op.drop_table('industry')
    op.drop_table('geography')
    op.drop_table('entity_stage')
    # ### end Alembic commands ###

    # Alembic autogenerate creates these ENUM types implicitly via column types
    # but never drops them on downgrade. Drop them so the migration is fully
    # reversible (otherwise a re-upgrade fails with "type already exists").
    for enum_name in (
        'entity_type', 'investment_stage', 'org_type', 'investor_type',
        'lead_preference', 'requeststatus', 'searchhistorytype', 'tier',
        'affiliation_role',
    ):
        op.execute('DROP TYPE IF EXISTS ' + enum_name)
