"""Initial migration.

Revision ID: 30fbd9f02f82
Revises: 
Create Date: 2024-01-30 17:49:33.503570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30fbd9f02f82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sa.String(), nullable=True))
        batch_op.drop_column('pfp_uuid')

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sa.String(), nullable=True))
        batch_op.drop_column('pfp_uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pfp_uuid', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('picture_url')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pfp_uuid', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('picture_url')

    # ### end Alembic commands ###
