"""empty message

Revision ID: 3ed6c2e7d073
Revises: ce3db9cc9591
Create Date: 2025-01-08 03:13:07.939991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed6c2e7d073'
down_revision = 'ce3db9cc9591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('custom_company_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('announced_date', sa.Date(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funding_round_id', sa.Integer(), nullable=True),
    sa.Column('investor_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('custom_name', sa.String(), nullable=True),
    sa.Column('investment_firm_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('created_by_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funding_round_id'], ['funding_round.id'], ),
    sa.ForeignKeyConstraint(['investment_firm_id'], ['investment_firm.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(), nullable=True))

    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_constraint('user_query', type_='unique')

    with op.batch_alter_table('user_company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_company', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_query', ['user_id', 'query'])

    with op.batch_alter_table('company_invitation', schema=None) as batch_op:
        batch_op.drop_column('position')

    op.drop_table('investment')
    op.drop_table('funding_round')
    # ### end Alembic commands ###
