"""empty message

Revision ID: 4e460892766d
Revises: f9da0a2faf7b
Create Date: 2024-11-06 03:07:27.322513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e460892766d'
down_revision = 'f9da0a2faf7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    def add_is_public_to_table(table_name):
        with op.batch_alter_table(table_name, schema=None) as batch_op:
            # 1. Add column as nullable
            op.add_column(f'{table_name}', sa.Column('is_public', sa.Boolean(), nullable=True))
            
            # 2. Update existing rows with default value
            op.execute(f"UPDATE {table_name} SET is_public = false")
            
            # 3. Set column to NOT NULL
            batch_op.alter_column('is_public',
                                existing_type=sa.Boolean(),
                                nullable=False)
            
    tables = ['investment_firm', 'investor', 'investor_backup', 'investor_origin_point',]
    
    for table in tables:
        add_is_public_to_table(table)

    op.create_table('company_bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('search_index', sa.String(), nullable=True))
        # 1. Add column as nullable
        op.add_column('company', sa.Column('is_public', sa.Boolean(), nullable=True))
        
        # 2. Update existing rows with a default value
        op.execute("UPDATE company SET is_public = false")
        
        # 3. Set column to NOT NULL
        op.alter_column('company', 'is_public',
                        existing_type=sa.Boolean(),
                        nullable=False)
        batch_op.create_unique_constraint(None, ['slug'])


    with op.batch_alter_table('notable_investment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('destination')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', postgresql.ENUM('ALL', 'SEARCH', 'ONBOARDING', 'COMPANY', 'VERIFICATION', 'INDEX', 'EXPANDED_ONBOARDING', name='notificationdestination'), autoincrement=False, nullable=True))

    with op.batch_alter_table('notable_investment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('investor_origin_point', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    with op.batch_alter_table('investor_backup', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    with op.batch_alter_table('investment_firm', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_public')
        batch_op.drop_column('search_index')
        batch_op.drop_column('slug')

    op.drop_table('company_bookmark')
    # ### end Alembic commands ###
