"""empty message

Revision ID: 561047b0267f
Revises: 4e460892766d
Create Date: 2024-11-14 12:12:30.970521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561047b0267f'
down_revision = '4e460892766d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), server_default='f', nullable=False))

    with op.batch_alter_table('investor_backup', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    with op.batch_alter_table('investor_origin_point', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_login')

    with op.batch_alter_table('investor_origin_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('investor_backup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
