"""empty message

Revision ID: 5a87f3055de1
Revises: 
Create Date: 2024-04-17 15:21:33.393067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a87f3055de1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_firm_notable_investment',
    sa.Column('investment_firm_id', sa.Integer(), nullable=False),
    sa.Column('notable_investment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investment_firm_id'], ['investment_firm.id'], ),
    sa.ForeignKeyConstraint(['notable_investment_id'], ['notable_investment.id'], ),
    sa.PrimaryKeyConstraint('investment_firm_id', 'notable_investment_id')
    )
    with op.batch_alter_table('investment_firm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_coordinates', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('search_index', sa.String(), nullable=True))

    with op.batch_alter_table('user_payment', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=postgresql.ENUM('FREE', 'PREMIUM_MONTHLY', 'PREMIUM_YEARLY', name='tier'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_payment', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=postgresql.ENUM('FREE', 'PREMIUM_MONTHLY', 'PREMIUM_YEARLY', name='tier'),
               nullable=True)

    with op.batch_alter_table('investment_firm', schema=None) as batch_op:
        batch_op.drop_column('search_index')
        batch_op.drop_column('bias')
        batch_op.drop_column('_coordinates')

    op.drop_table('investment_firm_notable_investment')
    # ### end Alembic commands ###
