"""empty message

Revision ID: 5c32ad357046
Revises: 83b34cbc27cc
Create Date: 2024-07-04 11:39:55.577547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c32ad357046'
down_revision = '83b34cbc27cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('status_info', sa.String(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investor.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investor_backup',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('firm_name', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('n_investments', sa.Integer(), nullable=True),
    sa.Column('n_exits', sa.Integer(), nullable=True),
    sa.Column('min_investment', sa.BigInteger(), nullable=True),
    sa.Column('max_investment', sa.BigInteger(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investor.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('investor_origin_point',
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('firm_name', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('n_investments', sa.Integer(), nullable=True),
    sa.Column('n_exits', sa.Integer(), nullable=True),
    sa.Column('min_investment', sa.BigInteger(), nullable=True),
    sa.Column('max_investment', sa.BigInteger(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('investor_backup_industry',
    sa.Column('investor_backup_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], ),
    sa.ForeignKeyConstraint(['investor_backup_id'], ['investor_backup.id'], ),
    sa.PrimaryKeyConstraint('investor_backup_id', 'industry_id')
    )
    op.create_table('investor_backup_notable_investment',
    sa.Column('investor_backup_id', sa.Integer(), nullable=False),
    sa.Column('notable_investment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investor_backup_id'], ['investor_backup.id'], ),
    sa.ForeignKeyConstraint(['notable_investment_id'], ['notable_investment.id'], ),
    sa.PrimaryKeyConstraint('investor_backup_id', 'notable_investment_id')
    )
    op.create_table('investor_backup_round',
    sa.Column('investor_backup_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investor_backup_id'], ['investor_backup.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('investor_backup_id', 'round_id')
    )
    op.create_table('investor_origin_point_industry',
    sa.Column('investor_origin_point_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industry.id'], ),
    sa.ForeignKeyConstraint(['investor_origin_point_id'], ['investor_origin_point.id'], ),
    sa.PrimaryKeyConstraint('investor_origin_point_id', 'industry_id')
    )
    op.create_table('investor_origin_point_notable_investment',
    sa.Column('investor_origin_point_id', sa.Integer(), nullable=False),
    sa.Column('notable_investment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investor_origin_point_id'], ['investor_origin_point.id'], ),
    sa.ForeignKeyConstraint(['notable_investment_id'], ['notable_investment.id'], ),
    sa.PrimaryKeyConstraint('investor_origin_point_id', 'notable_investment_id')
    )
    op.create_table('investor_origin_point_round',
    sa.Column('investor_origin_point_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investor_origin_point_id'], ['investor_origin_point.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('investor_origin_point_id', 'round_id')
    )
    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.drop_table('investor_origin_point_round')
    op.drop_table('investor_origin_point_notable_investment')
    op.drop_table('investor_origin_point_industry')
    op.drop_table('investor_backup_round')
    op.drop_table('investor_backup_notable_investment')
    op.drop_table('investor_backup_industry')
    op.drop_table('investor_origin_point')
    op.drop_table('investor_backup')
    op.drop_table('claim_request')
    # ### end Alembic commands ###
