"""empty message

Revision ID: 8038e102c15f
Revises: 886a73fb884d
Create Date: 2024-02-07 07:27:16.879662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8038e102c15f'
down_revision = '886a73fb884d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.drop_constraint('investor_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.create_unique_constraint('investor_email_key', ['email'])

    # ### end Alembic commands ###
