"""empty message

Revision ID: 83b34cbc27cc
Revises: ead866046ba6
Create Date: 2024-05-30 00:25:41.613862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b34cbc27cc'
down_revision = 'ead866046ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('linkedin_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('instagram_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('twitter_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_column('twitter_public')
        batch_op.drop_column('instagram_public')
        batch_op.drop_column('linkedin_public')
        batch_op.drop_column('email_public')

    # ### end Alembic commands ###
