"""empty message

Revision ID: 886a73fb884d
Revises: 30fbd9f02f82
Create Date: 2024-01-31 21:27:34.898645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886a73fb884d'
down_revision = '30fbd9f02f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_coordinates', sa.String(), nullable=True))

    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_coordinates', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bias', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investor', schema=None) as batch_op:
        batch_op.drop_column('bias')
        batch_op.drop_column('_coordinates')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('_coordinates')

    # ### end Alembic commands ###
