"""empty message

Revision ID: a687120402a9
Revises: 3ed6c2e7d073
Create Date: 2025-01-08 16:59:27.215070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a687120402a9'
down_revision = '3ed6c2e7d073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_investor_mode_active', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_investor_mode_active')

    # ### end Alembic commands ###
