"""empty message

Revision ID: f9da0a2faf7b
Revises: 0558ba631472
Create Date: 2024-07-22 02:17:08.474366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9da0a2faf7b'
down_revision = '0558ba631472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_verification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("ALTER TYPE companyrole ADD VALUE 'TEAM'")
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.String(), nullable=True))

    with op.batch_alter_table('company_invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('message', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['invited_by'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('role',
                        existing_type=sa.Enum('EMPLOYEE', 'TEAM', name='companyrole'),
                        type_=sa.Enum('TEAM', name='companyrole'),
                        existing_nullable=False)

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refuse_all_invitations', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_column('refuse_all_invitations')
    op.execute("UPDATE company_invitation SET role = 'EMPLOYEE' WHERE role = 'TEAM'")
    with op.batch_alter_table('company_invitation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('message')
        batch_op.drop_column('invited_by')
        batch_op.alter_column('role',
                existing_type=sa.Enum('TEAM', name='companyrole'),
                type_=sa.Enum('EMPLOYEE', 'TEAM', name='companyrole'),
                existing_nullable=False)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('linkedin_url')

    op.drop_table('claim_verification')
    # ### end Alembic commands ###
