"""empty message

Revision ID: dc7806e4f820
Revises: 
Create Date: 2023-07-31 14:29:06.751740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc7806e4f820"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "industrial_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "industry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "round",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("number_of_employees", sa.Integer(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("picture", sa.String(), nullable=True),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("preferred_round_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["country.id"],
        ),
        sa.ForeignKeyConstraint(
            ["preferred_round_id"],
            ["round.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("linkedin", sa.String(), nullable=True),
        sa.Column("instagram", sa.String(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company_industrial_group",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("industrial_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["industrial_group_id"],
            ["industrial_group.id"],
        ),
        sa.PrimaryKeyConstraint("company_id", "industrial_group_id"),
    )
    op.create_table(
        "company_industry",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("industry_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["industry_id"],
            ["industry.id"],
        ),
        sa.PrimaryKeyConstraint("company_id", "industry_id"),
    )
    with op.batch_alter_table("email_for_newsletter", schema=None) as batch_op:
        batch_op.alter_column(
            "email",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=255),
            existing_nullable=False,
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("picture")
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "first_name", sa.VARCHAR(length=30), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "last_name", sa.VARCHAR(length=30), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("picture", sa.VARCHAR(), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("email_for_newsletter", schema=None) as batch_op:
        batch_op.alter_column(
            "email",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )

    op.drop_table("company_industry")
    op.drop_table("company_industrial_group")
    op.drop_table("user_info")
    op.drop_table("company")
    op.drop_table("round")
    op.drop_table("industry")
    op.drop_table("industrial_group")
    op.drop_table("country")
    # ### end Alembic commands ###
