"""empty message

Revision ID: ddf9509068b7
Revises: dc7806e4f820
Create Date: 2023-07-31 20:02:27.377870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = "ddf9509068b7"
down_revision = "dc7806e4f820"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    oauthprovider = ENUM("google", "linkedin", name="oauthprovider")
    oauthprovider.create(op.get_bind(), checkfirst=False)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("oauth_provider", type_=oauthprovider, nullable=True)
        )

    with op.batch_alter_table("user_info", schema=None) as batch_op:
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=50), nullable=True
        )
        batch_op.alter_column(
            "first_name", existing_type=sa.VARCHAR(length=50), nullable=True
        )
        batch_op.alter_column(
            "last_name", existing_type=sa.VARCHAR(length=50), nullable=True
        )

        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_info", schema=None) as batch_op:
        batch_op.alter_column(
            "last_name", existing_type=sa.VARCHAR(length=50), nullable=False
        )
        batch_op.alter_column(
            "first_name", existing_type=sa.VARCHAR(length=50), nullable=False
        )
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=50), nullable=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("oauth_provider")

    # ### end Alembic commands ###
