name: Ruff

on:
    pull_request_review:
        types: [submitted]
    issue_comment:
        types: [created]

jobs:
    run-ruff:
        if: (github.event_name == 'pull_request_review' || (github.event_name == 'issue_comment' && github.event.comment.body == '/ruff')) && github.event.issue.pull_request
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.12"]
        steps:
            - name: Post comment that workflow has started
              uses: actions/github-script@v6
              with:
                  script: |
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: 'Ruff check has started.',
                        reply_to: context.event.comment.id
                      })
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install poetry
              uses: abatilo/actions-poetry@v2

            - name: Define a cache for the virtual environment based on the dependencies lock file
              uses: actions/cache@v3
              with:
                  path: ./.venv
                  key: venv-${{ hashFiles('poetry.lock') }}

            - name: Install dependencies
              run: poetry install --with dev

            - name: Running Ruff linter
              run: |
                  poetry run ruff check --fix || echo "Ruff check made changes" > ruff-status

            - name: Running Ruff formatter
              run: |
                  poetry run ruff format || echo "Ruff format made changes" > ruff-status

            - name: Commit and push if needed
              run: |
                  git diff
                  git config --global user.email "actions@github.com"
                  git config --global user.name "GitHub Action"
                  git commit -am "Apply ruff fixes" || exit 0
                  git push

            - name: Post comment if Ruff made changes
              uses: actions/github-script@v6
              if: steps.run-ruff.outcome == 'failure'
              with:
                  script: |
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: 'Ruff check made changes. Please review them.',
                        reply_to: context.event.comment.id
                      })
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
