name: Python testing

on:
    pull_request_review:
        types: [submitted]

jobs:
    run-tests:
        environment: python-testing
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version: ["3.12"]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install poetry
              uses: abatilo/actions-poetry@v2

            - name: Define a cache for the virtual environment based on the dependencies lock file
              uses: actions/cache@v3
              with:
                  path: ./.venv
                  key: venv-${{ hashFiles('poetry.lock') }}

            - name: Install dependencies
              run: poetry install

            - name: Run tests
              env:
                  _PUBSUB_TYPE: ${{ secrets._PUBSUB_TYPE }}
                  _PUBSUB_PROJECT_ID: ${{ secrets._PUBSUB_PROJECT_ID }}
                  _PUBSUB_PRIVATE_KEY_ID: ${{ secrets._PUBSUB_PRIVATE_KEY_ID }}
                  _PUBSUB_PRIVATE_KEY: ${{ secrets._PUBSUB_PRIVATE_KEY }}
                  _PUBSUB_CLIENT_EMAIL: ${{ secrets._PUBSUB_CLIENT_EMAIL }}
                  _PUBSUB_CLIENT_ID: ${{ secrets._PUBSUB_CLIENT_ID }}
                  _PUBSUB_AUTH_URI: ${{ secrets._PUBSUB_AUTH_URI }}
                  _PUBSUB_TOKEN_URI: ${{ secrets._PUBSUB_TOKEN_URI }}
                  _PUBSUB_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets._PUBSUB_AUTH_PROVIDER_X509_CERT_URL }}
                  _PUBSUB_CLIENT_X509_CERT_URL: ${{ secrets._PUBSUB_CLIENT_X509_CERT_URL }}
                  _PUBSUB_UNIVERSE_DOMAIN: ${{ secrets._PUBSUB_UNIVERSE_DOMAIN }}
              run: poetry run pytest -vvs -W ignore::DeprecationWarning
