name: Python testing

on:
    pull_request_review:
        types: [submitted]
    issue_comment:
        types: [created]

jobs:
    run-tests:
        if: (github.event_name == 'pull_request_review' || (github.event_name == 'issue_comment' && github.event.comment.body == '/tests')) && github.event.issue.pull_request
        environment: python-testing
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version: ["3.12"]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install poetry
              uses: abatilo/actions-poetry@v2

            - name: Define a cache for the virtual environment based on the dependencies lock file
              uses: actions/cache@v3
              with:
                  path: ./.venv
                  key: venv-${{ hashFiles('poetry.lock') }}

            - name: Install dependencies
              run: poetry install

            - name: Create Check Run
              id: create_check
              uses: octokit/request-action@v2.x
              with:
                  route: POST /repos/{owner}/{repo}/check-runs
                  mediaType: '{"previews": ["antiope"]}'
                  name: Test
                  head_sha: ${{ github.event.pull_request.head.sha }}
                  status: in_progress
                  started_at: ${{ github.event.pull_request.created_at }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Run tests
              env:
                  _PUBSUB_TYPE: ${{ secrets._PUBSUB_TYPE }}
                  _PUBSUB_PROJECT_ID: ${{ secrets._PUBSUB_PROJECT_ID }}
                  _PUBSUB_PRIVATE_KEY_ID: ${{ secrets._PUBSUB_PRIVATE_KEY_ID }}
                  _PUBSUB_PRIVATE_KEY: ${{ secrets._PUBSUB_PRIVATE_KEY }}
                  _PUBSUB_CLIENT_EMAIL: ${{ secrets._PUBSUB_CLIENT_EMAIL }}
                  _PUBSUB_CLIENT_ID: ${{ secrets._PUBSUB_CLIENT_ID }}
                  _PUBSUB_AUTH_URI: ${{ secrets._PUBSUB_AUTH_URI }}
                  _PUBSUB_TOKEN_URI: ${{ secrets._PUBSUB_TOKEN_URI }}
                  _PUBSUB_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets._PUBSUB_AUTH_PROVIDER_X509_CERT_URL }}
                  _PUBSUB_CLIENT_X509_CERT_URL: ${{ secrets._PUBSUB_CLIENT_X509_CERT_URL }}
                  _PUBSUB_UNIVERSE_DOMAIN: ${{ secrets._PUBSUB_UNIVERSE_DOMAIN }}
              run: poetry run pytest -vvs -W ignore::DeprecationWarning || echo "Tests failed" > test-status

            - name: Update Check Run
              uses: octokit/request-action@v2.x
              with:
                  route: PATCH /repos/{owner}/{repo}/check-runs/{check_run_id}
                  mediaType: '{"previews": ["antiope"]}'
                  check_run_id: ${{ steps.create_check.outputs.data.id }}
                  conclusion: ${{ if eq('Tests failed', 'Tests failed') }}failure${{ else }}success${{ end }}
                  completed_at: ${{ github.event.pull_request.updated_at }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
